global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

rule_files: []

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
        labels:
          app: "prometheus"

  - job_name: "node_exporter"
    static_configs:
      - targets: ["localhost:9100"]

  - job_name: "windows_dc"
    static_configs:
      - targets: ["172.16.0.1:9182"]
        labels:
          app: "windows_exporter"
          role: "domain_controller"

  - job_name: "windows_client"
    static_configs:
      - targets: ["172.16.0.11:9182"]
        labels:
          app: "windows_exporter"
          role: "client_pc"
